config/routes.rb
Rails.application.routes.draw do
  get 'playlists/search'    => 'playlists#index', as: 'search'
  post 'playlists/search'   => 'playlists#index'
  get 'playlists'           => 'playlists#index', as: 'playlists'
  post 'playlists'          => 'playlists#new', as: 'new_playlist'
  post 'playlists/:id/edit' => 'playlists#edit', as: 'edit_playlist'
  get 'playlists/:id'       => 'playlists#show', as: 'playlist'
  post 'playlists/:id'      => 'playlists#update'
  put 'playlists/:id'       => 'playlists#update'
  delete 'playlists/:id'    => 'playlists#destroy'

  root 'users#index'

  get '/auth/spotify/callback', :to => 'users#spotify'

  get '/profile', to: 'users#show', as: 'user'
  get '/music', to: 'users#music', as: 'music'

  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy', :as => "logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates :provider, :uid, :presence => true

  def self.find_or_create(auth_hash)
    unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"], auth_hash["user"])
      user = User.create :name => auth_hash["user_info"]["name"], :email => auth_hash["user_info"]["email"]
      auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end

    auth
  end
end

app/models/spotify.rb
class Spotify
  require 'rspotify'

  def self.search(search_type, q)
    options = {
        'track': self.track_search(q),
        'artist': self.artist_search(q),
        'album': self.album_search(q)
    }
    options[search_type]
  end

  def self.artist_search(query)
    p 'Artist search ...'
    response = RSpotify::Artist.search(query)
    p response.first.albums.first.tracks
    response
  end

  def self.track_search(query)
    RSpotify::Track.search(query)
  end

  def self.album_search(query)
    RSpotify::Album.search(query)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authorizations
  validates :name, :email, :presence => true

  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  include SessionsHelper
  include UsersHelper
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  require 'uri'

  def index
    if params[:query]
      q = URI.encode(params[:query])
      search_type = URI.encode(params[:choice].first)
      logger.info("Spotify query submitted: " + search_type)
      @results = Spotify.search(search_type, q)
    end
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # auth_hash = request.env['omniauth.auth']
    # puts "auth_hash contains: #{auth_hash}"
    # puts current_user
    # @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    # if @authorization
    #   render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
    # else
    #   user = User.new :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
    #   user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    #   user.save
    #   render :text => "Hi #{user.name}! You've signed up."
    # end
    # puts current_user
    # redirect_to user_path
  end

  def destroy
    session[:user_id] = nil
    logout
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
      @user = User.new
    end

  # def spotify
  #     @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
  #     hash = @spotify_user.to_hash
  #     puts hash
  #     puts @spotify_user.display_name
  #     render 'show'
  #   end

  def create
    if User.find_by({:email => user_params[:email]}) != nil
    flash[:error] = "User name already exists. Please try again"
    redirect_to root_path
  else
    @user = User.create(user_params)
    flash[:success] = "Welcome, #{@user.user_name}!"
    login(@user)
    redirect_to @user
  end
  end

  def show
    @user = User.find_by_id(params[:id])
      if (current_user != @user)
        flash[:error] = 'Stop Hacking!'
        redirect_to '/'
      end
  end

  def failure
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # def search
  #   @artists = RSpotify::Artist.search(params[:artist_name])
  #   @track = RSpotify::Track.search(params[:track_name])
  #   @album = RSpotify::Album.search(params[:album_name])
  #   @playlists = RSpotify::Playlist.search(params[:playlist_name])
  # end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/layouts/application.html.erb
<<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MASHAPP</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- STYLESHEETS -->
  <!-- HAVE TO INCLUDE VALIDATOR -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.js"></script>

  <!-- FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>



  <script src="https://code.jquery.com/jquery-3.2.1.js" ></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary rounded">
  <a class="navbar-brand" href="#page-top">MASHAPP</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link">Contact</a>
    </li>
  </ul>

  <% if current_user %>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link"><%= link_to "Profile", user_path(current_user)%></a>
    </li>
    <li class="navbar-item">
      <a class="nav-link"><%= link_to "Log out", logout_path %></a>
    </li>
  </ul>

    <%else%>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link"><%= link_to 'login', '/auth/spotify' %></a>
      </li>
    </ul>
    <%end%>
</nav>

<%=yield%>


<footer class="page-footer center-on-small-only unique-color-dark pt-0">

<div class="container mt-5 mb-4 text-center text-md-left">
<div class="row mt-3">

<div class="col-md-3 col-lg-4 col-xl-3 mb-r">
<h6 class="title font-bold"><strong>MASHAPP</strong></h6>
<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p>Short synopsis here</p>
</div>

<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-r">
<h6 class="title font-bold"><strong>Legal</strong></h6>
<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p><a href="https://termsfeed.com/terms-conditions/f1632a33674182c5c9c595f2783c5b1a">Terms</a></p>
</div>

<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-r">
<h6 class="title font-bold"><strong>Shoutouts</strong></h6>
<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p>WDI41</p>
<p>SHIPFAM</p>
</div>

<div class="col-md-4 col-lg-3 col-xl-3">
<h6 class="title font-bold"><strong>Contact</strong></h6>
<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p><i class="fa fa-home mr-3"></i> San Francisco, CA, US</p>
<p><i class="fa fa-envelope mr-3"></i><a href="mailto:maria.arbisman@gmail.com?Subject=MASHAPP" target="_top">Email</a></p>
<p><a class="icons-sm li-ic" href="https://linkedin.com/in/marbisman"><i class="fa fa-linkedin white-text mr-lg-4">in/marbisman</i></a></p>
<p><a href="https://github.com/marbisman"><i class="fa fa-github" aria-hidden="true"></i>@marbisman</i></a></p>
</div>


</div>
</div>

<div class="footer-copyright">
<div class="container-fluid">
<p>© 2017 Copyright:<strong> MASHAPP</strong></p>
</div>
</div>

</footer>

</body>
</html>

app/views/playlists/_results.html.erb
<% if @results %>
    <%= @results %>
  <ul>
    <% @results.each do |result| %>
        <li><%= result.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/playlists/_search.html.erb
<h1 class="page-header">Search</h1>
<%= form_with url: search_path, html: { class: "form" } do |f| %>
    <div class="form-group col-xs-4">
        <%= f.text_field 'query', placeholder: "Enter artist name", class: "form-control" %>
    </div>
    <div class="form-group col-xs-4">
      Artist<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'artist', false %>
      Track<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'track', false %>
      Album<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'album', false %>
    </div>

    <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

app/views/playlists/destroy.html.erb
<h1>Playlists#destroy</h1>
<p>Find me in app/views/playlists/destroy.html.erb</p>

app/views/playlists/index.html.erb
<h1>Collection Builder</h1>
<p>Search Spotify for tracks to add to your new playlists!</p>

<%= form_with url: search_path, html: { class: "form" } do |f| %>
    <div class="form-group col-xs-4">
      <%= f.text_field 'query', placeholder: "Enter artist name", class: "form-control" %>
    </div>
    <div class="form-group col-xs-4">
      Artist<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'artist', false %>
      Track<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'track', false %>
      Album<%= f.check_box :choice, { multiple: true, class: 'form-control' }, 'album', false %>
    </div>

    <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

<div id="results">
  <% if @results %>
      <%= @results %>
      <ul>
        <% @results.each do |result| %>
            <li><%= result.name %></li>
        <% end %>
      </ul>
  <% end %>

</div>

app/views/playlists/show.html.erb
<h1>Playlists#show</h1>
<p>Find me in app/views/playlists/show.html.erb</p>

app/views/playlists/update.html.erb
<h1>Playlists#update</h1>
<p>Find me in app/views/playlists/update.html.erb</p>

app/views/tracks/show.html.erb
<h1>Tracks#show</h1>
<p>Find me in app/views/tracks/show.html.erb</p>

app/views/users/_dashboard.html.erb
<h1> Hello, <%= @spotify_user.display_name %>, welcome back! </h1>

app/views/users/_search.html.erb
<h1 class="page-header">Search</h1>
<%= form_tag user_path, method: "get", html: { class: "form" } do %>
 <div class="form-group col-xs-4">
   <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
 </div>
 <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<h1><%= @artist.name %></h1>
<% @artist.albums(country: 'US').each do |album| %>
 <h3><%= album.name %></h3>
 <ul>
   <% album.tracks.each do |track| %>
     <li>
       <%= track.name %>
     </li>
   <% end %>
 </ul>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/failure.html.erb
<h1>Users#failure</h1>
<p>Find me in app/views/users/failure.html.erb</p>

app/views/users/index.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">MASHAPP</div>
      <div class="intro-heading text-uppercase">Search Music Your Way</div>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#about">Tell Me More</a>
    </div>
  </div>
</header>


   <!-- Contact -->
   <section id="contact">
     <div class="container">
       <div class="row">
         <div class="col-lg-12 text-center">
           <h2 class="section-heading text-uppercase">Contact Us</h2>
           <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
         </div>
       </div>
       <div class="row">
         <div class="col-lg-12">
           <form id="contactForm" name="sentMessage" novalidate>
             <div class="row">
               <div class="col-md-6">
                 <div class="form-group">
                   <input class="form-control" id="name" type="text" placeholder="Your Name *" required data-validation-required-message="Please enter your name.">
                   <p class="help-block text-danger"></p>
                 </div>
                 <div class="form-group">
                   <input class="form-control" id="email" type="email" placeholder="Your Email *" required data-validation-required-message="Please enter your email address.">
                   <p class="help-block text-danger"></p>
                 </div>
                 <div class="form-group">
                   <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" required data-validation-required-message="Please enter your phone number.">
                   <p class="help-block text-danger"></p>
                 </div>
               </div>
               <div class="col-md-6">
                 <div class="form-group">
                   <textarea class="form-control" id="message" placeholder="Your Message *" required data-validation-required-message="Please enter a message."></textarea>
                   <p class="help-block text-danger"></p>
                 </div>
               </div>
               <div class="clearfix"></div>
               <div class="col-lg-12 text-center">
                 <div id="success"></div>
                 <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
               </div>
             </div>
           </form>
         </div>
       </div>
     </div>
   </section>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/product.html.erb
<%= render "search" %>

app/views/users/show.html.erb
<%= render "dashboard" %>

<%= render "search"%>